### ISSUE TITLE
Navigation Panel 是獨立的 ScrollView，不要跟著 Content Panel 一起 Scroll

### ISSUE THREAD

**Issue by kun-yu-tsai** [nexfoundation/vanilla#107]
和設計師討論後，設計師提到當 content panel 的內容往下滑動時，左邊的 navigation 就跟著不見了，在體驗上可能有改善的空間。

建議的做法會是，讓左邊的 navigation panel 是一個獨立的 scroll view。

**Comment by blueworrybear** [comment]
@kun-yu-tsai 

Are you looking for something like:

![最近討論 — Vanilla - Google Chrome 2021-03-30 23-28-58](https://user-images.githubusercontent.com/1456219/113015320-03442000-91b0-11eb-8d61-73213a653b9e.gif)

It seems to me that we could implement this feature with CSS below:

```css
.Panel
 {
    position: sticky;
    top: 60px;
    overflow-y: scroll;
    min-width: 300px;
    height: calc(100vh - 60px - 60px);
}
```

However, I am not sure is a good idea. It's because:

1. We are using paging to limit the discussions in the page. The distance to scroll back to the top is not that far away.
2. There will be a ugly scrollbar, I don't think the original design looks great with that bar.

Therefore, I suggest to keep the current design.
